name: mycrm
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.35+35

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0+2
  oauth2: 1.2.3
  charts_flutter: 0.8.1
  flutter_slidable: "^0.5.3"
  dio: 3.0.0
  # dio_http_cache: ^0.1.4
  get_it: ^1.0.3
  flutter_datetime_picker: 1.5.0
  expandable: 3.0.0+1
  google_maps_webservice: 0.0.14
  font_awesome_flutter: 8.5.0
  url_launcher: 5.4.7
  # table_calendar:
  #   git:
  #   url: git://github.com/aleksanderwozniak/table_calendar.git
  #   ref: dev
  collection: 1.15.0-nullsafety.3
  queries: 0.1.12
  # connectivity: 0.4.5
  sqflite: 1.1.6+3
  json_annotation: 3.0.0
  progress_dialog: 1.2.0
  # json_serializable: ^3.0.0
  path: 1.6.4
  crypto: 2.1.4
  shared_preferences: 0.5.3
  flutter_local_notifications: 0.8.4
  fluttertoast: 3.1.3
  rxdart: 0.22.3
  intl: 0.15.8
  simple_gesture_detector: 0.1.3
  flutter_screenutil: 0.6.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  contacts_service: 0.3.5
  permission_handler: 3.3.0
  flutter_masked_text: 0.8.0
  flutter_money_formatter: 0.8.3
  flutter_launcher_icons: 0.7.3
  simple_animations: 1.3.3
  flutter_speed_dial: 1.2.3
  image_picker: 0.6.1+8
  firebase_ml_vision: 0.9.2+2
  speech_recognition: 0.3.0
  dynamic_theme: ^1.0.0
  flutter_email_sender: 2.1.0
  flutter_sms: 2.0.0
  package_info: 0.4.0+10
  share: 0.6.3+1
  flutter_image_compress: ^0.6.3
  path_provider: 1.4.0
  stripe_payment: 1.0.5
  webview_flutter: 0.3.15+1
  local_auth: 0.4.0+1
  file_picker: 1.4.2
  video_player: 0.10.1
  downloads_path_provider: 0.1.0
  open_file: 2.1.1
  google_maps_flutter: 0.5.21
  geocoder: ^0.2.1
  geolocator: ^5.1.5
  location_permissions: 2.0.3
  orientation: ^1.1.0
  chewie: 0.9.10
  # camera: 0.5.6+1

  
# dev_dependencies:
#   flutter_test:
#     sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/logo.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/style/fonts/OpenSans-Regular.ttf
        - asset: assets/style/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/style/fonts/Quicksand-Regular.ttf
        - asset: assets/style/fonts/Quicksand-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
