import 'package:flutter/material.dart';

class AppColors {
  static const List<Color> stageListPageColors = [
    Colors.blue,
    Colors.cyan,
    Colors.deepOrange,
    Colors.deepPurple,
    Colors.green,
    Colors.indigo,
    Colors.orange,
    Colors.red,
    Colors.teal,
    Colors.amber,
    Colors.orange,
    Colors.blueGrey,
    Colors.lime,
    Colors.brown,
    Colors.blue,
    Colors.cyan,
    Colors.deepOrange,
    Colors.deepPurple,
    Colors.green,
    Colors.indigo,
    Colors.orange,
    Colors.red,
    Colors.teal,
    Colors.amber,
    Colors.orange,
    Colors.blueGrey,
    Colors.lime,
    Colors.brown,
    Colors.blue,
    Colors.cyan,
    Colors.deepOrange,
    Colors.deepPurple,
    Colors.green,
    Colors.indigo,
    Colors.orange,
    Colors.red,
    Colors.teal,
    Colors.amber,
    Colors.orange,
    Colors.blueGrey,
    Colors.lime,
    Colors.brown,
     Colors.blue,
    Colors.cyan,
    Colors.deepOrange,
    Colors.deepPurple,
    Colors.green,
    Colors.indigo,
    Colors.orange,
    Colors.red,
    Colors.teal,
    Colors.amber,
    Colors.orange,
    Colors.blueGrey,
    Colors.lime,
    Colors.brown,
    Colors.blue,
    Colors.cyan,
    Colors.deepOrange,
    Colors.deepPurple,
    Colors.green,
    Colors.indigo,
    Colors.orange,
    Colors.red,
    Colors.teal,
    Colors.amber,
    Colors.orange,
    Colors.blueGrey,
    Colors.lime,
    Colors.brown,
    Colors.blue,
    Colors.cyan,
    Colors.deepOrange,
    Colors.deepPurple,
    Colors.green,
    Colors.indigo,
    Colors.orange,
    Colors.red,
    Colors.teal,
    Colors.amber,
    Colors.orange,
    Colors.blueGrey,
    Colors.lime,
    Colors.brown,
  ];
  static const normalTextColor = Colors.white;

  static const scheduleTitleColor = Colors.blueGrey;

  static const primaryColorNormal = Color.fromRGBO(182, 109, 109, 1);
  static const primaryColorDark = Color.fromRGBO(48, 44, 44, 1);
  static const primaryColorNormalLight = Color.fromRGBO(247, 221, 221, 1);
  static const primaryColorDarkLight = Color.fromRGBO(225, 217, 217, 1);
  static const primaryColorDarkDark = Color.fromRGBO(104, 84, 84, 1);
  static const primaryColorDarkLightLight = Colors.blueGrey;
}
